# Dockerfile.test

# Usar una imagen base de Python ligera
FROM python:3.10-slim

# Establecer el directorio de trabajo base
WORKDIR /app

# Copiar el archivo de dependencias e instalar
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de pruebas y el código fuente (aunque el volumen lo sobrescribirá)
# WORKDIR /app/tests
# COPY tests/ tests/
# COPY src/ /app/src/